### ISSUE TITLE
Assignment 1: Task List

### ISSUE THREAD

**Issue by Montuuh** [Montuuh/Gucci_Engines#1]
- [x] Baker_house should be automatically loaded at the start.
- [x] Your two models must be in FBX format with one channel diffuse texture.
- [x] It should accept drag&drop of FBX files from anywhere in the Hard Drive.
- [ ] It should accept drag&drop of DDS/PNG files (apply the texture to the selected GameObject).
- [ ] There must be a GameObject structure, one for each loaded mesh. Each GameObject should have,
at least, 3 display-only components: Transform, Mesh and Texture.

It should feature Unity-like camera controls:
> - [x] While Right clicking, “WASD” fps-like movement and free look around must be enabled.
> - [x] Mouse wheel should zoom in and out.
> - [ ] Alt+Left click should orbit the object.
> - [ ] Pressing “f” should focus the camera around the geometry.
> - [x] Holding SHIFT duplicates movement speed.

Editor Windows:
> - [x] Console: the window should LOG the geometry loading process from ASSIMP and the
external libraries initialization process

> Configuration:
> > - [x] A graph for the frames per second.
> > - [x] Configuration for all variables on each module (renderer, window, input, textures).
> > - [x] Information output of memory consumption, hardware detection and software
versions (SDL, OpenGL, DevIL).

> - [ ] Hierarchy: You should display a list with all GameObjects in this window. The user should be
able to select a GameObject through this window.

> Inspector: You should display information about the components of the selected GameObject:
> > - [ ] Transform: only for display purposes. Show position, rotation and scale for the
selected GameObject.
> > - [ ] Mesh: information about the loaded mesh. There should be an option to display its
normals (per-triangle and per-face).
> > - [ ] Texture: display texture size and path. There should be an option to view the
selected GameObject with the checkers texture

> - [x] There must be a general menu with an option to quit, visit the github page and get info about
the engine (“About”). It should also be able to turn on/off editor windows.

> - [x] There must be a menu to load your own basic shapes.
